version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-app
    container_name: sample_project-app
    image: sample_project/app:0.1.0
    ports:
      - "8080:8080"
    volumes:
      - ./src/app:/go/src/app
    depends_on:
      - redis
    tty: true

  redis:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile-db
    container_name: sample_project-db
    image: sample_project/db:0.1.0
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./docker/database:/data